"""Initial migration with all models

Revision ID: ef33059aae5e
Revises: 
Create Date: 2025-09-10 20:10:51.915589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef33059aae5e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role_permissions', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('role_permissions', 'permission_level',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('role_permissions', 'can_export',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('role_permissions', 'can_modify',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('role_permissions', 'can_delete',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('role_permissions', 'can_create',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('role_permissions', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('role_permissions', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_role_permissions_module'), 'role_permissions', ['module'], unique=False)
    op.create_index(op.f('ix_role_permissions_role'), 'role_permissions', ['role'], unique=False)
    op.create_unique_constraint('unique_role_module', 'role_permissions', ['role', 'module'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_role_module', 'role_permissions', type_='unique')
    op.drop_index(op.f('ix_role_permissions_role'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_module'), table_name='role_permissions')
    op.alter_column('role_permissions', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=True)
    op.alter_column('role_permissions', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=True)
    op.alter_column('role_permissions', 'can_create',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('role_permissions', 'can_delete',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('role_permissions', 'can_modify',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('role_permissions', 'can_export',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('role_permissions', 'permission_level',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'read'"),
               existing_nullable=False)
    op.alter_column('role_permissions', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
